//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Aufgabenverfolgung.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAuftragsverfolgungEntities : DbContext
    {
        public DbAuftragsverfolgungEntities()
            : base("name=DbAuftragsverfolgungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAbteilungen> TblAbteilungen { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAufgaben> TblAufgaben { get; set; }
        public virtual DbSet<TblAufgabendetails> TblAufgabendetails { get; set; }
        public virtual DbSet<TblFirmen> TblFirmen { get; set; }
        public virtual DbSet<TblPersonal> TblPersonal { get; set; }
    }
}
