//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Aufgabenverfolgung.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAufgaben
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAufgaben()
        {
            this.TblAufgabendetails = new HashSet<TblAufgabendetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Aufgabengeber { get; set; }
        public Nullable<int> Aufgabennehmer { get; set; }
        public string Kommentar { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual TblPersonal TblPersonal { get; set; }
        public virtual TblPersonal TblPersonal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAufgabendetails> TblAufgabendetails { get; set; }
    }
}
