//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Aufgabenverfolgung.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAufgabendetails
    {
        public int ID { get; set; }
        public Nullable<int> Aufgabe { get; set; }
        public string Kommentar { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Uhr { get; set; }
    
        public virtual TblAufgaben TblAufgaben { get; set; }
    }
}
