//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Aufgabenverfolgung.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFirmen
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string BerechtigtePerson { get; set; }
        public string TelNummer { get; set; }
        public string Mail { get; set; }
        public string Sektor { get; set; }
        public string Kress { get; set; }
        public string Stadt { get; set; }
        public string Adresse { get; set; }
    }
}
