//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Aufgabenverfolgung.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPersonal()
        {
            this.TblAufgaben = new HashSet<TblAufgaben>();
            this.TblAufgaben1 = new HashSet<TblAufgaben>();
        }
    
        public int ID { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string TelNummer { get; set; }
        public string Bild { get; set; }
        public Nullable<int> Abteilung { get; set; }
        public Nullable<bool> Statu { get; set; }
    
        public virtual TblAbteilungen TblAbteilungen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAufgaben> TblAufgaben { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAufgaben> TblAufgaben1 { get; set; }
    }
}
